---
packages:
  - build-essential
  - libreadline-dev
  - unzip
  - ripgrep
  - vim
  - make
  - cmake
  - curl
  - btop
  - ca-certificates
  - tilix
  - mesa-utils
  - nvtop
  - grub-customizer # For managing GRUB bootloader
