---
- hosts: localhost
  roles:
    - role: apt
      tags: [apt]
    - role: nvim
      tags: [nvim]
    - role: lua
      tags: [lua]
    - role: uv
      tags: [uv]
    - role: volta
      tags: [volta]
